export const serviceCategories = [
    {
        id: "music_services",
        category: "Music Services",
        subcategories: [
            { id: "music_production_writing", name: "Music Production & Writing" },
            { id: "producers_composers", name: "Producers & Composers" },
            { id: "songwriters", name: "Songwriters" },
            { id: "beat_making", name: "Beat Making" },
            { id: "singers_vocalists", name: "Singers & Vocalists" },
            { id: "audio_engineering_post", name: "Audio Engineering & Post Production" },
            { id: "mixing_mastering", name: "Mixing & Mastering" },
            { id: "audio_editing", name: "Audio Editing" },
            { id: "vocal_tuning", name: "Vocal Tuning" },
            { id: "audio_logo_branding", name: "Audio Logo & Sonic Branding" },
            { id: "voice_over_streaming", name: "Voice Over & Streaming" },
            { id: "voice_over", name: "Voice Over" },
            { id: "podcast_production", name: "Podcast Production" },
            { id: "audiobook_production", name: "Audiobook Production" },
            { id: "audio_ads", name: "Audio Ads Production" },
            { id: "djing", name: "DJing" },
            { id: "remixing_mashups", name: "Remixing & Mashups" },
            { id: "dj_drops_tags", name: "DJ Drops & Tags" },
            { id: "dj_mixing", name: "DJ Mixing" },
            { id: "virtual_djing", name: "Virtual DJing" }
        ]
    },
    {
        id: "visual_arts",
        category: "Visual Arts",
        subcategories: [
            { id: "logo_brand_identity", name: "Logo & Brand Identity" },
            { id: "logo_design", name: "Logo Design" },
            { id: "brand_style_guides", name: "Brand Style Guides" },
            { id: "business_cards", name: "Business Cards & Stationery" },
            { id: "icon_design", name: "Icon Design" },
            { id: "web_app_design", name: "Web & App Design" },
            { id: "website_design", name: "Website Design" },
            { id: "app_design", name: "App Design" },
            { id: "ux_design", name: "UX Design" },
            { id: "landing_page_design", name: "Landing Page Design" },
            { id: "art_illustration", name: "Art & Illustration" },
            { id: "illustration", name: "Illustration" },
            { id: "children_illustration", name: "Children’s Book Illustration" },
            { id: "portraits_caricatures", name: "Portraits & Caricatures" },
            { id: "cartoons_comics", name: "Cartoons & Comics" },
            { id: "print_marketing", name: "Print & Marketing Design" },
            { id: "flyer_design", name: "Flyer Design" },
            { id: "brochure_design", name: "Brochure Design" },
            { id: "poster_design", name: "Poster Design" },
            { id: "social_media_design", name: "Social Media Design" }
        ]
    },
    {
        id: "performing_arts",
        category: "Performing Arts",
        subcategories: [
            { id: "dance", name: "Dance" },
            { id: "contemporary_dance", name: "Contemporary Dance" },
            { id: "choreography", name: "Choreography" },
            { id: "dance_lessons", name: "Dance Lessons" },
            { id: "dance_performances", name: "Dance Performances" },
            { id: "theater", name: "Theater" },
            { id: "drama", name: "Drama" },
            { id: "musicals", name: "Musicals" },
            { id: "theater_directing", name: "Theater Directing" },
            { id: "playwriting", name: "Playwriting" },
            { id: "standup_comedy", name: "Stand-up Comedy" },
            { id: "comedy_writing", name: "Comedy Writing" },
            { id: "comedy_performances", name: "Comedy Performances" },
            { id: "comedy_coaching", name: "Comedy Coaching" },
            { id: "comedy_specials", name: "Comedy Specials" },
            { id: "video_shoutouts", name: "Video Shoutouts" },
            { id: "personalized_greetings", name: "Personalized Greetings" },
            { id: "celebrity_messages", name: "Celebrity Video Messages" },
            { id: "special_event_messages", name: "Special Event Messages" },
            { id: "custom_videos", name: "Custom Videos" }
        ]
    },
    {
        id: "entertainment_content",
        category: "Entertainment Content",
        subcategories: [
            { id: "screenwriting", name: "Screenwriting" },
            { id: "film_scripts", name: "Film Scripts" },
            { id: "tv_scripts", name: "Television Scripts" },
            { id: "short_story_scripts", name: "Short Story Scripts" },
            { id: "web_series_scripts", name: "Web Series Scripts" },
            { id: "podcasting", name: "Podcasting" },
            { id: "podcast_editing", name: "Podcast Editing" },
            { id: "podcast_hosting", name: "Podcast Hosting" },
            { id: "podcast_scripting", name: "Podcast Scripting" },
            { id: "documentary_production", name: "Documentary Production" },
            { id: "documentary_planning", name: "Documentary Planning" },
            { id: "documentary_editing", name: "Documentary Editing" },
            { id: "documentary_directing", name: "Documentary Directing" },
            { id: "documentary_voiceovers", name: "Documentary Voiceovers" },
            { id: "video_content_creation", name: "Video Content Creation" },
            { id: "promotional_videos", name: "Promotional Videos" },
            { id: "event_videography", name: "Event Videography" },
            { id: "short_films", name: "Short Films" },
            { id: "music_videos", name: "Music Videos" }
        ]
    },
    {
        id: "online_event_services",
        category: "Online Event Services",
        subcategories: [
            { id: "virtual_event_planning", name: "Virtual Event Planning" },
            { id: "virtual_wedding_planning", name: "Virtual Wedding Planning" },
            { id: "virtual_corporate_events", name: "Virtual Corporate Events" },
            { id: "virtual_conferences", name: "Virtual Conferences" },
            { id: "virtual_seminars", name: "Virtual Seminars" },
            { id: "virtual_event_promotion", name: "Virtual Event Promotion" },
            { id: "social_media_promotion", name: "Social Media Promotion" },
            { id: "email_campaigns", name: "Email Campaigns" },
            { id: "paid_ad_campaigns", name: "Paid Ad Campaigns" },
            { id: "influencer_promotion", name: "Influencer Promotion" },
            { id: "virtual_event_tech", name: "Virtual Event Tech Services" },
            { id: "virtual_stage_design", name: "Virtual Stage Design" },
            { id: "virtual_stream_setup", name: "Virtual Event Stream Setup" },
            { id: "audio_visual_setup", name: "Audio-Visual Setup" },
            { id: "tech_support", name: "Tech Support" },
            { id: "virtual_event_hosting", name: "Virtual Event Hosting" },
            { id: "event_moderation", name: "Event Moderation" },
            { id: "guest_speaking", name: "Guest Speaking" },
            { id: "panel_hosting", name: "Panel Discussion Hosting" },
            { id: "qa_management", name: "Q&A Management" }
        ]
    },
    {
        id: "digital_media",
        category: "Digital Media",
        subcategories: [
            { id: "digital_marketing", name: "Digital Marketing" },
            { id: "seo_services", name: "SEO Services" },
            { id: "ppc_campaigns", name: "PPC Campaigns" },
            { id: "social_media_marketing", name: "Social Media Marketing" },
            { id: "email_marketing", name: "Email Marketing" },
            { id: "social_media_management", name: "Social Media Management" },
            { id: "content_planning", name: "Content Planning" },
            { id: "post_scheduling", name: "Post Scheduling" },
            { id: "social_media_analytics", name: "Social Media Analytics" },
            { id: "audience_engagement", name: "Audience Engagement" },
            { id: "content_creation", name: "Content Creation" },
            { id: "blog_writing", name: "Blog Writing" },
            { id: "video_creation", name: "Video Creation" },
            { id: "graphic_design", name: "Graphic Design" },
            { id: "infographics", name: "Infographics" },
            { id: "influencer_marketing", name: "Influencer Marketing" },
            { id: "brand_partnerships", name: "Brand Partnerships" },
            { id: "sponsored_posts", name: "Sponsored Posts" },
            { id: "influencer_outreach", name: "Influencer Outreach" },
            { id: "product_placement", name: "Product Placement" }
        ]
    },
    {
        id: "fashion",
        category: "Fashion",
        subcategories: [
            { id: "fashion_design", name: "Fashion Design" },
            { id: "apparel_design", name: "Apparel Design" },
            { id: "accessory_design", name: "Accessory Design" },
            { id: "fashion_illustration", name: "Fashion Illustration" },
            { id: "fashion_consultation", name: "Fashion Consultation & Styling" },
            { id: "custom_sneaker_design", name: "Custom Sneaker Design" },
            { id: "hand_painted_designs", name: "Hand-painted Designs" },
            { id: "sneaker_restoration", name: "Sneaker Restoration" },
            { id: "limited_edition_designs", name: "Limited Edition Designs" },
            { id: "sneaker_prototyping", name: "Sneaker Prototyping" },
            { id: "fashion_photography", name: "Fashion Photography" },
            { id: "editorial_photography", name: "Editorial Photography" },
            { id: "lookbook_photography", name: "Lookbook Photography" },
            { id: "runway_photography", name: "Runway Photography" },
            { id: "product_photography", name: "Product Photography" },
            { id: "fashion_marketing", name: "Fashion Marketing" },
            { id: "social_media_marketing_fashion", name: "Social Media Marketing" },
            { id: "branding_pr", name: "Branding & PR" },
            { id: "fashion_show_planning", name: "Fashion Show Planning" },
            { id: "influencer_collaborations", name: "Influencer Collaborations" }
        ]
    },
    {
        id: "gaming_esports",
        category: "Gaming & eSports",
        subcategories: [
            { id: "game_streaming", name: "Game Streaming Services" },
            { id: "live_streaming", name: "Live Streaming" },
            { id: "game_playthroughs", name: "Game Playthroughs" },
            { id: "streaming_setup", name: "Streaming Setup" },
            { id: "streaming_content", name: "Streaming Content Creation" },
            { id: "esport_coaching", name: "eSport Coaching" },
            { id: "strategy_coaching", name: "Strategy Coaching" },
            { id: "game_skill_improvement", name: "Game Skill Improvement" },
            { id: "team_dynamics", name: "Team Dynamics" },
            { id: "tournament_preparation", name: "Tournament Preparation" },
            { id: "game_graphics_design", name: "Game Graphics & Design" },
            { id: "game_character_design", name: "Game Character Design" },
            { id: "game_environment_design", name: "Game Environment Design" },
            { id: "game_ux_ui", name: "Game UX/UI" },
            { id: "game_animation", name: "Game Animation" },
            { id: "game_development", name: "Game Development" },
            { id: "game_coding", name: "Game Coding" },
            { id: "game_testing", name: "Game Testing" },
            { id: "game_prototyping", name: "Game Prototyping" },
            { id: "indie_game_dev", name: "Indie Game Development" }
        ]
    }
];