export const cardsData = [
  {
    image: "https://via.placeholder.com/300x150?text=MongoDB",
    name: "Osama",
    description: "I will help you write complex queries and optimize your database.",
    rating: "4.9 (32)",
    price: "$ 1,461",
    videoConsultation: false,
    category:"category-1",
    subCategory:"subcategory-1-3",
    keyword: [
      "Fshion",
      "Tech Support",
      "Online Event Stream Setup",
      "Database Optimization",
      "Complex Queries",
      "Audio-Visual Setup",
    ],
  },
  {
    image: "https://via.placeholder.com/300x150?text=Custom+Thumbnail",
    name: "Test34",
    description: "I will create an awesome YouTube thumbnail in 3 hours.",
    rating: "4.9 (496)",
    price: "$ 2,921",
    level: "Level 2",
    videoConsultation: false,
    category:"category-2",
    subCategory:"subcategory-2-3",
    keyword: [
      "Graphic Design",
      "Social Media Design",
      "Creative Marketing & Strategy",
      "Lookbook Photography",
      "Fashion Marketing",
    ],
  },
  {
    image: "https://via.placeholder.com/300x150?text=Custom+Thumbnail",
    name: "Test5",
    description: "I will create an awesome YouTube thumbnail in 3 hours.",
    rating: "4.9 (496)",
    price: "$ 2,921",
    level: "Level 2",
    videoConsultation: false,
    category:"category-5",
    subCategory:"subcategory-5-3",
    keyword: [
      'subcategory-5-1',
      "Graphic Design",
      "Social Media Design",
      "Digital Media",
      "Creative Marketing & Strategy",
      "Lookbook Photography",
      "Fashion Marketing",
    ],
  },
  {
    image: "https://via.placeholder.com/300x150?text=Custom+Thumbnail",
    name: "Osama",
    description: "I will create an awesome YouTube thumbnail in 3 hours.",
    rating: "4.9 (496)",
    price: "$ 2,921",
    level: "Level 2",
    videoConsultation: false,
    category:"category-3",
    subCategory:"subcategory-3-3",
    keyword: [
      "subcategory-3-1",
      "Graphic Design",
      "Social Media Design",
      "Digital Media",
      "Creative Marketing & Strategy",
      "Lookbook Photography",
      "Fashion Marketing",
    ],
  },
  {
    image: "https://via.placeholder.com/300x150?text=Custom+Thumbnail",
    name: "Test1",
    description: "I will create an awesome YouTube thumbnail in 3 hours.",
    rating: "4.9 (496)",
    price: "$ 2,921",
    level: "Level 2",
    videoConsultation: false,
    category:"category-3",
    subCategory:"subcategory-3-2",
    keyword: [
      "Graphic Design",
      "Social Media Design",
      "Digital Media",
      "Creative Marketing & Strategy",
      "Lookbook Photography",
      "Fashion Marketing",
      "subcategory-3-1",
    ],
  },
  {
    image: "https://via.placeholder.com/300x150?text=Pelyform",
    name: "Pelyform",
    description: "I will do API development and integration.",
    rating: "5.0 (41)",
    price: "$ 58,407",
    level: "Level 2",
    videoConsultation: true,
    category:"category-2",
    subCategory:"subcategory-2-3",
    keyword: [
      "API Development",
      "API Integration",
      "Tech Support",
      "Event Tech Setup",
      "Online Event Management",
      "subcategory-2-3"
    ],
  },
  {
    image: "https://via.placeholder.com/300x150?text=NodeJS",
    name: "Osama",
    description: "I will develop any Node.js application or API and fix bugs.",
    rating: "5.0 (23)",
    price: "$ 4,381",
    level: "Level 2",
    category:"category-3",
    subCategory:"subcategory-3-3",
    videoConsultation: false,
    keyword: [
      "Node.js Development",
      "API Development",
      "Bug Fixing",
      "Tech Support",
      "Online Event Stream Setup",
      "subcategory-3-6"
    ],
  },
  {
    image: "https://via.placeholder.com/300x150?text=Pelyform",
    name: "Osama Test",
    description: "I will do API development and integration.",
    rating: "5.0 (41)",
    price: "$ 58,407",
    level: "Level 2",
    category:"category-3",
    videoConsultation: true,
    keyword: [
      "API Development",
      "Backend Services",
      "Event Planning",
      "Tech Support",
      "Audio-Visual Setup",
    ],
  },
  {
    image: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAJ8AqQMBIgACEQEDEQH/xAAcAAEAAwADAQEAAAAAAAAAAAAABQYHAgQIAwH/xABAEAABAwMBBAYHBQUJAQAAAAABAAIDBAURBhIhMWEHIkFRcYETFDZyc7GzIzJikaFCU4KywRUzNVJUkpPS8EP/xAAZAQEAAwEBAAAAAAAAAAAAAAAAAQIDBAX/xAAsEQEAAgIABAMHBQEAAAAAAAAAAQIDEQQSITEyQXETIlFSYYHBM5Gh0eEU/9oADAMBAAIRAxEAPwDcUREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERB//9k=",
    name: "Osama test",
    description: "I will develop any Node.js application or API and fix bugs.",
    rating: "5.0 (23)",
    price: "$ 4,381",
    level: "Level 2",
    category:"category-3",
    subCategory:"subcategory-3-1",
    videoConsultation: false,
    keyword: [
      "subcategory-3-4",
      "Node.js Development",
      "Backend Development",
      "Bug Fixing",
      "Online Stage Design",
      "Tech Support",
    ],
  },
];
